name: Conventional Commits Validator
author: João Cerqueira
description: Validates a Pull Request title and commit messages against Conventional Commits guidelines

branding:
  icon: check-circle
  color: purple

runs:
  using: composite
  steps:
    - run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash