name: Conventional Commits
description: Checks if a Pull Request and commits follow Conventional Commits

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash