name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
