name: Test

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
